name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  HAIKU_HOST: taurus.microgeni.synology.me
  HAIKU_USER: user
  HAIKU_PROJECT_PATH: /Data/Code/Projects/softKM

jobs:
  build:
    name: Build
    runs-on: macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes
        id: changes
        run: |
          # Check if this is a release (tag push)
          IS_RELEASE="false"
          VERSION=""
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            IS_RELEASE="true"
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"  # Remove 'v' prefix
            echo "Release build: version $VERSION"
          fi
          echo "is_release=$IS_RELEASE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # For releases, always build both platforms
          if [ "$IS_RELEASE" = "true" ]; then
            MACOS_CHANGED=1
            HAIKU_CHANGED=1
          else
            # Check what directories have changes
            MACOS_CHANGED=$(git diff --name-only HEAD~1 -- MacOS/ 2>/dev/null | wc -l | tr -d ' ')
            HAIKU_CHANGED=$(git diff --name-only HEAD~1 -- HaikuOS/ 2>/dev/null | wc -l | tr -d ' ')

            # If workflow file changed, build both
            WORKFLOW_CHANGED=$(git diff --name-only HEAD~1 -- .gitea/workflows/ 2>/dev/null | wc -l | tr -d ' ')

            if [ "$WORKFLOW_CHANGED" -gt 0 ]; then
              MACOS_CHANGED=1
              HAIKU_CHANGED=1
            fi
          fi

          echo "macos_changed=$MACOS_CHANGED" >> $GITHUB_OUTPUT
          echo "haiku_changed=$HAIKU_CHANGED" >> $GITHUB_OUTPUT
          echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "MacOS changes: $MACOS_CHANGED, Haiku changes: $HAIKU_CHANGED, Branch: ${{ github.ref_name }}, Release: $IS_RELEASE"

      - name: Setup Keychain
        if: steps.changes.outputs.macos_changed != '0' || github.event_name == 'workflow_dispatch'
        env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
        run: |
          # Create a temporary keychain for CI
          KEYCHAIN_PATH="$RUNNER_TEMP/signing.keychain-db"
          KEYCHAIN_PASSWORD="ci-signing-temp"

          # Decode the certificate
          echo "$CERTIFICATE_P12" | base64 --decode > "$RUNNER_TEMP/certificate.p12"

          # Create and configure keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # Import certificate (password: softKM2025)
          security import "$RUNNER_TEMP/certificate.p12" \
            -P "softKM2025" \
            -A \
            -t cert \
            -f pkcs12 \
            -k "$KEYCHAIN_PATH"

          # Set keychain search list
          security list-keychains -d user -s "$KEYCHAIN_PATH" ~/Library/Keychains/login.keychain-db
          security default-keychain -s "$KEYCHAIN_PATH"

          # Allow codesign to access the keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # Clean up certificate file
          rm -f "$RUNNER_TEMP/certificate.p12"

          # List available signing identities
          echo "Available signing identities:"
          security find-identity -v -p codesigning

      - name: Build macOS App
        if: steps.changes.outputs.macos_changed != '0' || github.event_name == 'workflow_dispatch'
        run: |
          cd MacOS
          BUILD_NUMBER="${{ github.run_number }}"
          IS_RELEASE="${{ steps.changes.outputs.is_release }}"
          echo "Building with build number: $BUILD_NUMBER, Release: $IS_RELEASE"

          # Always use Developer ID signing
          xcodebuild -project softKM.xcodeproj \
            -scheme softKM \
            -configuration Release \
            -derivedDataPath build \
            CURRENT_PROJECT_VERSION=$BUILD_NUMBER \
            CODE_SIGN_STYLE="Manual" \
            CODE_SIGN_IDENTITY="Developer ID Application: Microgeni hb (Z5DSCKN2W6)" \
            DEVELOPMENT_TEAM="Z5DSCKN2W6" \
            OTHER_CODE_SIGN_FLAGS="--timestamp" \
            CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO \
            clean build

      - name: Install macOS App
        if: steps.changes.outputs.macos_changed != '0' || github.event_name == 'workflow_dispatch'
        run: |
          APP_PATH="MacOS/build/Build/Products/Release/softKM.app"
          if [ -d "$APP_PATH" ]; then
            pkill -x softKM || true
            sleep 1
            rm -rf /Applications/softKM.app
            # Use ditto to preserve code signature and extended attributes
            ditto "$APP_PATH" /Applications/softKM.app
            # Verify signature after copy
            codesign -v /Applications/softKM.app && echo "Code signature valid" || echo "WARNING: Code signature invalid"
            echo "macOS app installed to /Applications/softKM.app"
          else
            echo "Build output not found at $APP_PATH"
            exit 1
          fi

      - name: Launch macOS App
        if: (steps.changes.outputs.macos_changed != '0' || github.event_name == 'workflow_dispatch') && steps.changes.outputs.is_release != 'true'
        run: |
          open /Applications/softKM.app
          echo "macOS app launched"

      - name: Create macOS DMG
        if: steps.changes.outputs.is_release == 'true'
        run: |
          VERSION="${{ steps.changes.outputs.version }}"
          APP_PATH="MacOS/build/Build/Products/Release/softKM.app"
          DMG_NAME="softKM-${VERSION}-macOS.dmg"

          echo "Creating DMG: $DMG_NAME"

          # Verify app signature before packaging
          echo "Verifying app signature..."
          codesign -vvv --deep --strict "$APP_PATH"

          # Create a temporary directory for the DMG contents
          mkdir -p dmg_contents
          cp -R "$APP_PATH" dmg_contents/
          ln -s /Applications dmg_contents/Applications

          # Create the DMG
          hdiutil create -volname "softKM $VERSION" \
            -srcfolder dmg_contents \
            -ov -format UDZO \
            "$DMG_NAME"

          rm -rf dmg_contents

          # Sign the DMG
          echo "Signing DMG..."
          codesign --force --sign "Developer ID Application: Microgeni hb (Z5DSCKN2W6)" "$DMG_NAME"
          codesign -vvv "$DMG_NAME"

          echo "DMG created and signed: $DMG_NAME"
          ls -la "$DMG_NAME"

          # Store DMG path for later upload
          echo "dmg_path=$DMG_NAME" >> $GITHUB_OUTPUT
        id: macos_dmg

      - name: Notarize macOS DMG
        if: steps.changes.outputs.is_release == 'true'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
        run: |
          VERSION="${{ steps.changes.outputs.version }}"
          DMG_NAME="softKM-${VERSION}-macOS.dmg"

          echo "=== Notarizing $DMG_NAME ==="

          # Submit for notarization and capture output
          SUBMIT_OUTPUT=$(xcrun notarytool submit "$DMG_NAME" \
            --apple-id "$APPLE_ID" \
            --team-id "$APPLE_TEAM_ID" \
            --password "$APPLE_APP_PASSWORD" \
            --wait 2>&1) || true

          echo "$SUBMIT_OUTPUT"

          # Extract submission ID
          SUBMISSION_ID=$(echo "$SUBMIT_OUTPUT" | grep "id:" | head -1 | awk '{print $2}')
          echo "Submission ID: $SUBMISSION_ID"

          # Check if notarization succeeded
          if echo "$SUBMIT_OUTPUT" | grep -q "status: Accepted"; then
            echo "Notarization succeeded!"
          else
            echo "=== Notarization failed, fetching log ==="
            if [ -n "$SUBMISSION_ID" ]; then
              xcrun notarytool log "$SUBMISSION_ID" \
                --apple-id "$APPLE_ID" \
                --team-id "$APPLE_TEAM_ID" \
                --password "$APPLE_APP_PASSWORD"
            fi
            exit 1
          fi

          # Staple the notarization ticket
          echo "Stapling notarization ticket..."
          xcrun stapler staple "$DMG_NAME"

          echo "=== Notarization complete ==="

      - name: Deploy to Haiku
        if: (steps.changes.outputs.haiku_changed != '0' || github.event_name == 'workflow_dispatch') && steps.changes.outputs.is_release != 'true'
        run: |
          ssh -o StrictHostKeyChecking=no $HAIKU_USER@$HAIKU_HOST << 'ENDSSH'
            set -e
            echo "=== Deploying softKM to Haiku ==="

            if [ ! -d "/Data/Code/Projects/softKM" ]; then
              echo "Project not found. Cloning..."
              mkdir -p /Data/Code/Projects
              cd /Data/Code/Projects
              git clone ssh://git@gitea.microgeni.synology.me:2222/daniel/softKM.git softKM
            fi
            cd /Data/Code/Projects/softKM

            echo "Pulling latest changes from ${{ github.ref_name }}..."
            git fetch origin
            git checkout -f ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}

            echo "Stopping existing softKM..."
            for pid in $(ps | grep softKM | grep -v grep | awk '{print $2}'); do
              kill $pid 2>/dev/null || true
            done
            sleep 2

            cd HaikuOS
            if [ -d "objects.x86_64-release" ]; then
              cp -r objects.x86_64-release objects.x86_64-release.backup 2>/dev/null || true
            fi

            echo "Building Haiku app..."
            make clean
            make

            BINARY=$(find objects.* -name "softKM" -type f 2>/dev/null | head -1)
            if [ -z "$BINARY" ]; then
              echo "Build failed - no binary found"
              if [ -d "objects.x86_64-release.backup" ]; then
                mv objects.x86_64-release.backup objects.x86_64-release
              fi
              exit 1
            fi

            echo "Build successful: $BINARY"

            echo "Building input_server addons..."
            cd addon
            make clean
            make

            echo "Installing addons..."
            mkdir -p ~/config/non-packaged/add-ons/input_server/devices
            # Remove old combined addon if it exists
            rm -f ~/config/non-packaged/add-ons/input_server/devices/SoftKMDevice 2>/dev/null || true

            KEYBOARD_ADDON=$(find objects.* -name "SoftKMKeyboard" -type f 2>/dev/null | head -1)
            MOUSE_ADDON=$(find objects.* -name "SoftKMMouse" -type f 2>/dev/null | head -1)

            if [ -n "$KEYBOARD_ADDON" ] && [ -n "$MOUSE_ADDON" ]; then
              cp "$KEYBOARD_ADDON" ~/config/non-packaged/add-ons/input_server/devices/
              cp "$MOUSE_ADDON" ~/config/non-packaged/add-ons/input_server/devices/
              echo "Addons installed: $KEYBOARD_ADDON, $MOUSE_ADDON"
              echo "NOTE: Reboot Haiku to load updated input_server addons"
            else
              echo "Warning: Addon build failed"
            fi
            cd ..

            echo "Launching softKM..."
            nohup $BINARY > /dev/null 2>&1 &

            sleep 3
            if ps | grep -v grep | grep -q softKM; then
              echo "softKM is running!"
            else
              echo "Warning: softKM may not have started correctly"
            fi

            rm -rf objects.x86_64-release.backup 2>/dev/null || true
            echo "=== Deployment complete ==="
          ENDSSH

      - name: Create Haiku HPKG
        if: steps.changes.outputs.is_release == 'true'
        run: |
          VERSION="${{ steps.changes.outputs.version }}"
          BUILD_NUMBER="${{ github.run_number }}"
          HPKG_NAME="softKM-${VERSION}-haiku-x86_64.hpkg"

          echo "Creating HPKG: $HPKG_NAME"

          ssh -o StrictHostKeyChecking=no $HAIKU_USER@$HAIKU_HOST << ENDSSH
            set -e
            echo "=== Building Haiku release package ==="

            cd /Data/Code/Projects/softKM

            # Fetch and checkout the tag (force to handle tag updates)
            git fetch origin --tags --force
            git checkout -f v${VERSION}

            # Build the app
            cd HaikuOS
            make clean
            make

            # Build addons
            cd addon
            make clean
            make
            cd ..

            # Update .PackageInfo with correct version
            sed -i "s/^version.*/version\t\t\t${VERSION}-${BUILD_NUMBER}/" .PackageInfo
            sed -i "s/softKM = .*/softKM = ${VERSION}-${BUILD_NUMBER}/" .PackageInfo
            sed -i "s/app:softKM = .*/app:softKM = ${VERSION}-${BUILD_NUMBER}/" .PackageInfo

            # Create package directory structure
            rm -rf package_temp
            mkdir -p package_temp/apps
            mkdir -p package_temp/add-ons/input_server/devices

            # Copy built files
            BINARY=\$(find objects.* -name "softKM" -type f 2>/dev/null | head -1)
            cp "\$BINARY" package_temp/apps/

            # Copy addons
            KEYBOARD_ADDON=\$(find addon/objects.* -name "SoftKMKeyboard" -type f 2>/dev/null | head -1)
            MOUSE_ADDON=\$(find addon/objects.* -name "SoftKMMouse" -type f 2>/dev/null | head -1)
            if [ -n "\$KEYBOARD_ADDON" ]; then
              cp "\$KEYBOARD_ADDON" package_temp/add-ons/input_server/devices/
            fi
            if [ -n "\$MOUSE_ADDON" ]; then
              cp "\$MOUSE_ADDON" package_temp/add-ons/input_server/devices/
            fi

            # Copy .PackageInfo
            cp .PackageInfo package_temp/

            # Create HPKG
            cd package_temp
            package create -b ../${HPKG_NAME}
            cd ..

            echo "HPKG created: ${HPKG_NAME}"
            ls -la ${HPKG_NAME}

            rm -rf package_temp
          ENDSSH

          # Copy HPKG back to runner
          scp -o StrictHostKeyChecking=no $HAIKU_USER@$HAIKU_HOST:/Data/Code/Projects/softKM/HaikuOS/${HPKG_NAME} .

          echo "HPKG downloaded: $HPKG_NAME"
          ls -la "$HPKG_NAME"

          echo "hpkg_path=$HPKG_NAME" >> $GITHUB_OUTPUT
        id: haiku_hpkg

      - name: Upload Release to Gitea
        if: steps.changes.outputs.is_release == 'true'
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          VERSION="${{ steps.changes.outputs.version }}"
          TAG="v${VERSION}"
          REPO="daniel/softKM"
          API_URL="https://gitea.microgeni.synology.me/api/v1"

          echo "=== Creating Release $TAG ==="

          # Create release
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $RELEASE_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"$TAG\", \"name\": \"$TAG\", \"body\": \"Release $VERSION\n\n## Downloads\n- macOS: softKM-${VERSION}-macOS.dmg\n- Haiku: softKM-${VERSION}-haiku-x86_64.hpkg\", \"draft\": false, \"prerelease\": false}" \
            "$API_URL/repos/$REPO/releases")

          echo "Release response: $RELEASE_RESPONSE"

          # Extract release ID
          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | grep -o '"id":[0-9]*' | head -1 | cut -d: -f2)

          if [ -z "$RELEASE_ID" ]; then
            echo "Failed to create release or get release ID"
            # Try to get existing release
            RELEASE_ID=$(curl -s -H "Authorization: token $RELEASE_TOKEN" \
              "$API_URL/repos/$REPO/releases/tags/$TAG" | grep -o '"id":[0-9]*' | head -1 | cut -d: -f2)
          fi

          echo "Release ID: $RELEASE_ID"

          if [ -n "$RELEASE_ID" ]; then
            # Upload macOS DMG
            DMG_FILE="softKM-${VERSION}-macOS.dmg"
            if [ -f "$DMG_FILE" ]; then
              echo "Uploading $DMG_FILE..."
              curl -s -X POST \
                -H "Authorization: token $RELEASE_TOKEN" \
                -H "Content-Type: application/octet-stream" \
                --data-binary @"$DMG_FILE" \
                "$API_URL/repos/$REPO/releases/$RELEASE_ID/assets?name=$DMG_FILE"
              echo "Uploaded $DMG_FILE"
            fi

            # Upload Haiku HPKG
            HPKG_FILE="softKM-${VERSION}-haiku-x86_64.hpkg"
            if [ -f "$HPKG_FILE" ]; then
              echo "Uploading $HPKG_FILE..."
              curl -s -X POST \
                -H "Authorization: token $RELEASE_TOKEN" \
                -H "Content-Type: application/octet-stream" \
                --data-binary @"$HPKG_FILE" \
                "$API_URL/repos/$REPO/releases/$RELEASE_ID/assets?name=$HPKG_FILE"
              echo "Uploaded $HPKG_FILE"
            fi

            echo "=== Release published: $TAG ==="
          else
            echo "ERROR: Could not get release ID"
            exit 1
          fi

      - name: Summary
        if: always()
        run: |
          echo "=== Build Summary ==="
          echo "Ref: ${{ github.ref_name }}"
          echo "Build Number: ${{ github.run_number }}"

          IS_RELEASE="${{ steps.changes.outputs.is_release }}"
          if [ "$IS_RELEASE" = "true" ]; then
            echo "Type: RELEASE v${{ steps.changes.outputs.version }}"
          else
            echo "Type: Development build"
          fi

          MACOS_CHANGES="${{ steps.changes.outputs.macos_changed != '0' }}"
          HAIKU_CHANGES="${{ steps.changes.outputs.haiku_changed != '0' }}"

          if [ "$MACOS_CHANGES" = "true" ]; then
            if [ "$IS_RELEASE" = "true" ]; then
              echo "macOS: Built and packaged (DMG)"
            else
              echo "macOS: Built and installed"
            fi
          else
            echo "macOS: Skipped (no changes)"
          fi

          if [ "$HAIKU_CHANGES" = "true" ]; then
            if [ "$IS_RELEASE" = "true" ]; then
              echo "Haiku: Built and packaged (HPKG)"
            else
              echo "Haiku: Built and deployed"
            fi
          else
            echo "Haiku: Skipped (no changes)"
          fi

          echo ""
          echo "Status: ${{ job.status }}"
