name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  HAIKU_HOST: taurus.microgeni.synology.me
  HAIKU_USER: user
  HAIKU_PROJECT_PATH: /Data/Code/Projects/softKM

jobs:
  build:
    name: Build
    runs-on: macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes
        id: changes
        run: |
          # Check what directories have changes
          MACOS_CHANGED=$(git diff --name-only HEAD~1 -- MacOS/ 2>/dev/null | wc -l | tr -d ' ')
          HAIKU_CHANGED=$(git diff --name-only HEAD~1 -- HaikuOS/ 2>/dev/null | wc -l | tr -d ' ')

          # If workflow file changed, build both
          WORKFLOW_CHANGED=$(git diff --name-only HEAD~1 -- .gitea/workflows/ 2>/dev/null | wc -l | tr -d ' ')

          if [ "$WORKFLOW_CHANGED" -gt 0 ]; then
            MACOS_CHANGED=1
            HAIKU_CHANGED=1
          fi

          echo "macos_changed=$MACOS_CHANGED" >> $GITHUB_OUTPUT
          echo "haiku_changed=$HAIKU_CHANGED" >> $GITHUB_OUTPUT
          echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "MacOS changes: $MACOS_CHANGED, Haiku changes: $HAIKU_CHANGED, Branch: ${{ github.ref_name }}"

      - name: Build macOS App
        if: steps.changes.outputs.macos_changed != '0' || github.event_name == 'workflow_dispatch'
        run: |
          cd MacOS
          xcodebuild -project softKM.xcodeproj \
            -scheme softKM \
            -configuration Release \
            -derivedDataPath build \
            clean build

      - name: Install macOS App
        if: steps.changes.outputs.macos_changed != '0' || github.event_name == 'workflow_dispatch'
        run: |
          APP_PATH="MacOS/build/Build/Products/Release/softKM.app"
          if [ -d "$APP_PATH" ]; then
            pkill -x softKM || true
            sleep 1
            rm -rf /Applications/softKM.app
            # Use ditto to preserve code signature and extended attributes
            ditto "$APP_PATH" /Applications/softKM.app
            # Verify signature after copy
            codesign -v /Applications/softKM.app && echo "Code signature valid" || echo "WARNING: Code signature invalid"
            echo "macOS app installed to /Applications/softKM.app"
          else
            echo "Build output not found at $APP_PATH"
            exit 1
          fi

      - name: Launch macOS App
        if: steps.changes.outputs.macos_changed != '0' || github.event_name == 'workflow_dispatch'
        run: |
          open /Applications/softKM.app
          echo "macOS app launched"

      - name: Deploy to Haiku
        if: steps.changes.outputs.haiku_changed != '0' || github.event_name == 'workflow_dispatch'
        run: |
          ssh -o StrictHostKeyChecking=no $HAIKU_USER@$HAIKU_HOST << 'ENDSSH'
            set -e
            echo "=== Deploying softKM to Haiku ==="

            if [ ! -d "/Data/Code/Projects/softKM" ]; then
              echo "Project not found. Cloning..."
              mkdir -p /Data/Code/Projects
              cd /Data/Code/Projects
              git clone ssh://git@gitea.microgeni.synology.me:2222/daniel/softKM.git softKM
            fi
            cd /Data/Code/Projects/softKM

            echo "Pulling latest changes from ${{ github.ref_name }}..."
            git fetch origin
            git checkout ${{ github.ref_name }} 2>/dev/null || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}

            echo "Stopping existing softKM..."
            for pid in $(ps | grep softKM | grep -v grep | awk '{print $2}'); do
              kill $pid 2>/dev/null || true
            done
            sleep 2

            cd HaikuOS
            if [ -d "objects.x86_64-release" ]; then
              cp -r objects.x86_64-release objects.x86_64-release.backup 2>/dev/null || true
            fi

            echo "Building Haiku app..."
            make clean
            make

            BINARY=$(find objects.* -name "softKM" -type f 2>/dev/null | head -1)
            if [ -z "$BINARY" ]; then
              echo "Build failed - no binary found"
              if [ -d "objects.x86_64-release.backup" ]; then
                mv objects.x86_64-release.backup objects.x86_64-release
              fi
              exit 1
            fi

            echo "Build successful: $BINARY"

            echo "Building input_server addons..."
            cd addon
            make clean
            make

            echo "Installing addons..."
            mkdir -p ~/config/non-packaged/add-ons/input_server/devices
            # Remove old combined addon if it exists
            rm -f ~/config/non-packaged/add-ons/input_server/devices/SoftKMDevice 2>/dev/null || true

            KEYBOARD_ADDON=$(find objects.* -name "SoftKMKeyboard" -type f 2>/dev/null | head -1)
            MOUSE_ADDON=$(find objects.* -name "SoftKMMouse" -type f 2>/dev/null | head -1)

            if [ -n "$KEYBOARD_ADDON" ] && [ -n "$MOUSE_ADDON" ]; then
              cp "$KEYBOARD_ADDON" ~/config/non-packaged/add-ons/input_server/devices/
              cp "$MOUSE_ADDON" ~/config/non-packaged/add-ons/input_server/devices/
              echo "Addons installed: $KEYBOARD_ADDON, $MOUSE_ADDON"

              echo "Restarting input_server to load addons..."
              /system/servers/input_server -q
              sleep 3
              # Verify input_server restarted
              if ps | grep -v grep | grep -q input_server; then
                echo "input_server restarted successfully"
              else
                echo "Warning: input_server may not have restarted"
              fi
            else
              echo "Warning: Addon build failed"
            fi
            cd ..

            echo "Launching softKM..."
            nohup $BINARY > /dev/null 2>&1 &

            sleep 3
            if ps | grep -v grep | grep -q softKM; then
              echo "softKM is running!"
            else
              echo "Warning: softKM may not have started correctly"
            fi

            rm -rf objects.x86_64-release.backup 2>/dev/null || true
            echo "=== Deployment complete ==="
          ENDSSH

      - name: Summary
        if: always()
        run: |
          echo "=== Build Summary ==="
          echo "Branch: ${{ github.ref_name }}"

          MACOS_CHANGES="${{ steps.changes.outputs.macos_changed != '0' }}"
          HAIKU_CHANGES="${{ steps.changes.outputs.haiku_changed != '0' }}"

          if [ "$MACOS_CHANGES" = "true" ]; then
            echo "macOS: Built and installed"
          else
            echo "macOS: Skipped (no changes)"
          fi

          if [ "$HAIKU_CHANGES" = "true" ]; then
            echo "Haiku: Built and deployed"
          else
            echo "Haiku: Skipped (no changes)"
          fi

          if [ "$MACOS_CHANGES" = "false" ] && [ "$HAIKU_CHANGES" = "false" ]; then
            echo ""
            echo "Status: No builds performed (no relevant changes detected)"
          else
            echo ""
            echo "Status: ${{ job.status }}"
          fi
